[package]
name = "commonware-avs-router"
version.workspace = true
edition.workspace = true

[dependencies]
alloy = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
commonware-actor = { workspace = true }
commonware-avs-bindings = { path = "../bindings" }
commonware-avs-core = { path = "../core" }
commonware-codec = { workspace = true }
commonware-consensus = { workspace = true }
commonware-cryptography = { workspace = true }
commonware-p2p = { workspace = true }
commonware-parallel = { workspace = true }
commonware-runtime = { workspace = true }
commonware-utils = { workspace = true }
eigen-crypto-bls = { workspace = true }
futures = { workspace = true }
rand_core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
