apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "commonware-avs.shareddata.fullname" . }}
  labels:
    {{- include "commonware-avs.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.sharedData.accessMode }}
  {{- if .Values.sharedData.storageClass }}
  storageClassName: {{ .Values.sharedData.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sharedData.size }}