[package]
name = "counter-solana-deployer"
version = { workspace = true }
edition = "2021"
publish = false

[[bin]]
name = "counter-solana-deployer"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
borsh = "0.10.3"
clap = { workspace = true }
hex = { workspace = true }
jito-restaking-core = { workspace = true }
jito-restaking-sdk = { workspace = true }
jito-vault-core = { workspace = true }
jito-vault-sdk = { workspace = true }
ncn-program-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-client = { workspace = true }
solana-program = { workspace = true }
solana-sdk = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true }
