#!/usr/bin/env bash
#
# solana_e2e_local.sh — ONE command boots the full Solana/Jito e2e stack:
#
#   solana-test-validator (real jito restaking + vault programs BUILT FROM
#   SOURCE at rev 358fbc3c + the NCN program + the gaskiller-settlement
#   program built from BreadchainCoop/jito-ncn-program main) -> deployer
#   (configs, NCN, 4 operators, full handshake mesh, vault, delegations, real
#   BLS proof-of-possession registrations, settlement InitializeState) ->
#   restart the validator with --warp-slot into epoch 2 (jito SlotToggles need
#   `current_epoch > activation_epoch + 1` and epoch_length is HARDCODED to
#   432,000 slots at InitializeConfig — no admin ix exists to change it; the
#   warp-restart compresses the empty epochs while every state transition
#   stays a real transaction) -> vault + snapshot cranks -> router + 4 node
#   processes reach BLS quorum on a digest -> JitoSubmitter lands
#   VerifyCertificate -> ASSERT the successful transaction on-chain at
#   `confirmed`.
#
# Then the LLM SETTLEMENT LEG (INTERFACES.md §4/§6, default on, E2E_LLM=0 to
# skip): the REAL Gas Killer LLM fixture (a pinned 10.5B-gas Solidity
# `tellStory("Once upon a time")` run) is regenerated by the
# llm-payload-producer CLI against the REAL state PDA + settle discriminator,
# the 457-byte story is staged into the digest-verified buffer account in >=2
# WriteBuffer chunks, the SAME 4-operator committee certifies the payload
# digest, the router lands `Settle{payload, certificate}`, and the script
# asserts at `confirmed`: commitment_root == the story root,
# transition_count == 1, sha256(buffer) == story_sha256, the story_meta
# self-CPI event, the story read back from chain, and the replay gate
# (resubmitting the identical Settle fails InvalidTransitionIndex).
#
# NO mocks, NO fake programs, real BLS certificates, real registrations.
#
# Requirements: Agave toolchain 4.1.x (solana-test-validator, cargo-build-sbf),
# rust, git. Everything else is built from source by this script.
#
# Env overrides:
#   E2E_WORK_DIR           artifacts + ledger + logs   (default: <repo>/.solana-e2e)
#   JITO_RESTAKING_SRC     existing clone of jito-foundation/restaking @ 358fbc3c
#   NCN_PROGRAM_SRC        existing clone of BreadchainCoop/jito-ncn-program main
#   E2E_KEEP_LEDGER=1      keep the ledger dir on exit (large!)
#   E2E_TICKS_PER_SLOT     validator ticks per slot (default 16)
#   E2E_LLM=0              skip the LLM settlement leg
#   E2E_KEEP_ALIVE=1       (or --keep-alive) on SUCCESS: stop the committee
#                          processes but leave the validator + ledger up, so
#                          the frontend (or the Playwright smoke) can read the
#                          settled story from the live RPC afterwards

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        --keep-alive) E2E_KEEP_ALIVE=1 ;;
        *) echo "unknown argument: $arg" >&2; exit 2 ;;
    esac
done
E2E_KEEP_ALIVE="${E2E_KEEP_ALIVE:-0}"

# ---------------------------------------------------------------------------
# Pins — single source of truth for source provenance
# ---------------------------------------------------------------------------
JITO_RESTAKING_REV="358fbc3c20d947c977a136808f9fbf7f070e478b"
JITO_RESTAKING_REPO="https://github.com/jito-foundation/restaking.git"
NCN_PROGRAM_REPO="https://github.com/BreadchainCoop/jito-ncn-program.git"
# The Qwen leg needs the qwen-producer branch (adds `--mode qwen` to the payload
# producer + the checked-in qwen06_capital_of_france.json fixture). It is branched
# off the same main rev as the settlement merge, so the NCN + settlement programs
# build identically. Override NCN_PROGRAM_REF=main + LLM_MODEL=story for the story leg.
NCN_PROGRAM_REF="${NCN_PROGRAM_REF:-qwen-producer}"
# LLM settlement leg model: `qwen` (§8, real Qwen3-0.6B answer, inline ids) or
# `story` (§4, buffered stories260K story).
LLM_MODEL="${LLM_MODEL:-qwen}"

RESTAKING_PROGRAM_ID="RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"
VAULT_PROGRAM_ID="Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"
NCN_PROGRAM_ID="3fKQSi6VzzDUJSmeksS8qK6RB3Gs3UoZWtsQD3xagy45"
# The gaskiller-settlement program's declare_id! (fixed in its source).
SETTLEMENT_PROGRAM_ID="6XTdBk798fEpM2VPBXpkLPw4zJJLvASaiyHaEmj9Ripx"
E2E_LLM="${E2E_LLM:-1}"

# Jito epoch geometry (hardcoded in the programs at this rev).
EPOCH_LENGTH=432000
WARP_SLOT=$((2 * EPOCH_LENGTH + 100)) # first slots of epoch 2

RPC_URL="http://127.0.0.1:8899"
ROUTER_PORT=3100
NODE_BASE_PORT=3101
NUM_OPERATORS=4
TICKS_PER_SLOT="${E2E_TICKS_PER_SLOT:-16}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
WORK="${E2E_WORK_DIR:-$ROOT/.solana-e2e}"
OUT="$WORK/out"
LEDGER="$WORK/ledger"
LOGS="$WORK/logs"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/solana-e2e-src"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
say()  { echo -e "${YELLOW}[e2e]${NC} $*"; }
ok()   { echo -e "${GREEN}[e2e]${NC} $*"; }
fail() { echo -e "${RED}[e2e] $*${NC}"; exit 1; }

PIDS=()
cleanup() {
    local code=$?
    if [[ $code -eq 0 && "$E2E_KEEP_ALIVE" == "1" ]]; then
        say "keep-alive: stopping committee processes, leaving the validator up"
        for pid in "${PIDS[@]:-}"; do kill "$pid" 2>/dev/null || true; done
        pkill -f "counter-solana-node --key-file $OUT" 2>/dev/null || true
        pkill -f "counter-solana-router --key-file $OUT" 2>/dev/null || true
        ok "validator still running at $RPC_URL (ledger: $LEDGER)"
        ok "frontend config: $OUT/frontend-config.json"
        ok "teardown: pkill -f 'solana-test-validator --ledger $LEDGER'; rm -rf '$LEDGER'"
        exit 0
    fi
    say "cleanup (exit $code)"
    for pid in "${PIDS[@]:-}"; do kill "$pid" 2>/dev/null || true; done
    pkill -f "counter-solana-node --key-file $OUT" 2>/dev/null || true
    pkill -f "counter-solana-router --key-file $OUT" 2>/dev/null || true
    pkill -f "solana-test-validator --ledger $LEDGER" 2>/dev/null || true
    sleep 1
    if [[ "${E2E_KEEP_LEDGER:-0}" != "1" ]]; then rm -rf "$LEDGER"; fi
    if [[ $code -ne 0 ]]; then
        echo "--- router log tail ---";  tail -30 "$LOGS/router.log"  2>/dev/null || true
        echo "--- node-0 log tail ---";  tail -15 "$LOGS/node-0.log"  2>/dev/null || true
        echo "--- llm router log tail ---"; tail -30 "$LOGS/llm-router.log" 2>/dev/null || true
        echo "--- llm node-0 log tail ---"; tail -15 "$LOGS/llm-node-0.log" 2>/dev/null || true
        echo "--- validator log tail ---"; tail -10 "$LOGS/validator-b.log" 2>/dev/null || true
    fi
    exit $code
}
trap cleanup EXIT INT TERM

# ---------------------------------------------------------------------------
# Step 0: toolchain preflight
# ---------------------------------------------------------------------------
SOLANA_BIN="$HOME/.local/share/solana/install/active_release/bin"
[[ -d "$SOLANA_BIN" ]] && export PATH="$SOLANA_BIN:$PATH"
for tool in solana-test-validator cargo-build-sbf solana cargo git; do
    command -v "$tool" >/dev/null 2>&1 || fail "$tool not found on PATH (install Agave: sh -c \"\$(curl -sSfL https://release.anza.xyz/v4.1.1/install)\")"
done
say "toolchain: $(solana --version | head -1)"
mkdir -p "$WORK" "$OUT" "$LOGS" "$CACHE"

# jito-ncn-program (the ncn-program-core git dep) pins a SUBMODULE by SSH url
# (git@github.com:Unboxed-Software/commonware-avs-router-solana). On a clean
# machine cargo's fetch of the dep fails to clone that submodule without SSH
# auth. Route cargo's git work through the git CLI with a process-scoped
# https rewrite (no global config mutation; the repo is public).
export CARGO_NET_GIT_FETCH_WITH_CLI=true
export GIT_CONFIG_COUNT=1
export GIT_CONFIG_KEY_0="url.https://github.com/.insteadOf"
export GIT_CONFIG_VALUE_0="git@github.com:"

# ---------------------------------------------------------------------------
# Step 1: build the three programs FROM SOURCE
# ---------------------------------------------------------------------------
RESTAKING_SRC="${JITO_RESTAKING_SRC:-$CACHE/restaking-$JITO_RESTAKING_REV}"
if [[ ! -d "$RESTAKING_SRC/.git" ]]; then
    say "cloning jito-foundation/restaking @ $JITO_RESTAKING_REV"
    git init -q "$RESTAKING_SRC"
    git -C "$RESTAKING_SRC" remote add origin "$JITO_RESTAKING_REPO"
    git -C "$RESTAKING_SRC" fetch -q --depth 1 origin "$JITO_RESTAKING_REV"
    git -C "$RESTAKING_SRC" checkout -q FETCH_HEAD
fi
HEAD_REV="$(git -C "$RESTAKING_SRC" rev-parse HEAD)"
[[ "$HEAD_REV" == "$JITO_RESTAKING_REV" ]] || fail "restaking src at $HEAD_REV, expected $JITO_RESTAKING_REV"

RESTAKING_SO="$RESTAKING_SRC/target/deploy/jito_restaking_program.so"
VAULT_SO="$RESTAKING_SRC/target/deploy/jito_vault_program.so"
if [[ ! -f "$RESTAKING_SO" || ! -f "$VAULT_SO" ]]; then
    say "building jito restaking + vault programs (cargo-build-sbf, env-injected program ids)"
    (cd "$RESTAKING_SRC" \
        && RESTAKING_PROGRAM_ID="$RESTAKING_PROGRAM_ID" VAULT_PROGRAM_ID="$VAULT_PROGRAM_ID" \
           cargo-build-sbf --manifest-path restaking_program/Cargo.toml \
        && RESTAKING_PROGRAM_ID="$RESTAKING_PROGRAM_ID" VAULT_PROGRAM_ID="$VAULT_PROGRAM_ID" \
           cargo-build-sbf --manifest-path vault_program/Cargo.toml)
fi
ok "jito programs: $(basename "$RESTAKING_SO") $(stat -f%z "$RESTAKING_SO" 2>/dev/null || stat -c%s "$RESTAKING_SO") B, $(basename "$VAULT_SO") $(stat -f%z "$VAULT_SO" 2>/dev/null || stat -c%s "$VAULT_SO") B"

NCN_SRC="${NCN_PROGRAM_SRC:-$CACHE/jito-ncn-program}"
if [[ ! -d "$NCN_SRC/.git" ]]; then
    say "cloning BreadchainCoop/jito-ncn-program @ $NCN_PROGRAM_REF"
    git clone -q --branch "$NCN_PROGRAM_REF" "$NCN_PROGRAM_REPO" "$NCN_SRC"
    # The workspace needs the router submodule present to load; rewrite the
    # SSH submodule URL to https (public repo).
    git -C "$NCN_SRC" config url."https://github.com/".insteadOf "git@github.com:"
    git -C "$NCN_SRC" submodule update --init commonware-avs-router-solana
elif [[ -z "${NCN_PROGRAM_SRC:-}" ]]; then
    # Cache-managed clone: keep it on the tip of the tracked ref (a restored
    # CI cache may predate the settlement program / payload producer).
    say "updating cached jito-ncn-program clone to origin/$NCN_PROGRAM_REF"
    git -C "$NCN_SRC" fetch -q origin "$NCN_PROGRAM_REF"
    git -C "$NCN_SRC" checkout -q -B "$NCN_PROGRAM_REF" FETCH_HEAD
    git -C "$NCN_SRC" submodule update --init commonware-avs-router-solana
fi
NCN_SO="$WORK/ncn_program.so"
if [[ ! -f "$NCN_SO" || -n "$(find "$NCN_SRC/program/src" -newer "$NCN_SO" 2>/dev/null | head -1)" ]]; then
    say "building NCN program (cargo-build-sbf) from $(git -C "$NCN_SRC" rev-parse --short HEAD)"
    (cd "$NCN_SRC" && cargo build-sbf --manifest-path program/Cargo.toml --sbf-out-dir "$WORK")
fi
ok "ncn program: $(stat -f%z "$NCN_SO" 2>/dev/null || stat -c%s "$NCN_SO") B"

SETTLEMENT_SO="$WORK/settlement_program.so"
if [[ "$E2E_LLM" == "1" ]]; then
    if [[ ! -f "$SETTLEMENT_SO" \
        || -n "$(find "$NCN_SRC/settlement_program/src" "$NCN_SRC/settlement_core/src" -newer "$SETTLEMENT_SO" 2>/dev/null | head -1)" ]]; then
        say "building gaskiller-settlement program (cargo-build-sbf)"
        (cd "$NCN_SRC" && cargo build-sbf --manifest-path settlement_program/Cargo.toml --sbf-out-dir "$WORK")
    fi
    ok "settlement program: $(stat -f%z "$SETTLEMENT_SO" 2>/dev/null || stat -c%s "$SETTLEMENT_SO") B"

    # The §6 payload producer CLI (regenerates the payload against the REAL
    # state PDA + settle discriminator; the story/root stay the pinned
    # fixture's ground truth).
    PRODUCER="$NCN_SRC/target/debug/llm-payload-producer"
    if [[ ! -x "$PRODUCER" \
        || -n "$(find "$NCN_SRC/llm_payload_producer/src" -newer "$PRODUCER" 2>/dev/null | head -1)" ]]; then
        say "building llm-payload-producer CLI"
        (cd "$NCN_SRC" && cargo build -p llm-payload-producer)
    fi
    if [[ "$LLM_MODEL" == "qwen" ]]; then
        LLM_FIXTURE="$NCN_SRC/llm_payload_producer/fixtures/qwen06_capital_of_france.json"
    else
        LLM_FIXTURE="$NCN_SRC/llm_payload_producer/fixtures/tell_story_once_upon_a_time.json"
    fi
    [[ -f "$LLM_FIXTURE" ]] || fail "checked-in LLM fixture missing: $LLM_FIXTURE"
    say "LLM leg model: $LLM_MODEL (fixture $(basename "$LLM_FIXTURE"))"
fi

# ---------------------------------------------------------------------------
# Step 2: build the off-chain binaries
# ---------------------------------------------------------------------------
say "building deployer + node + router binaries"
(cd "$ROOT" && cargo build -p counter-solana-deployer -p counter-solana-node -p counter-solana-router)
DEPLOYER="$ROOT/target/debug/counter-solana-deployer"
NODE_BIN="$ROOT/target/debug/counter-solana-node"
ROUTER_BIN="$ROOT/target/debug/counter-solana-router"

# ---------------------------------------------------------------------------
# Step 3: validator phase A (genesis, epoch 0)
# ---------------------------------------------------------------------------
start_validator() {
    local log="$1"; shift
    local programs=(
        --bpf-program "$RESTAKING_PROGRAM_ID" "$RESTAKING_SO"
        --bpf-program "$VAULT_PROGRAM_ID" "$VAULT_SO"
        --bpf-program "$NCN_PROGRAM_ID" "$NCN_SO"
    )
    if [[ "$E2E_LLM" == "1" ]]; then
        programs+=(--bpf-program "$SETTLEMENT_PROGRAM_ID" "$SETTLEMENT_SO")
    fi
    solana-test-validator --ledger "$LEDGER" \
        --ticks-per-slot "$TICKS_PER_SLOT" \
        "${programs[@]}" \
        --quiet "$@" &> "$log" &
    VALIDATOR_PID=$!
}

wait_rpc() {
    local deadline=$((SECONDS + 120))
    until solana slot -u "$RPC_URL" &>/dev/null; do
        [[ $SECONDS -lt $deadline ]] || fail "validator RPC not up within 120s"
        kill -0 "$VALIDATOR_PID" 2>/dev/null || fail "validator process died (see logs)"
        sleep 2
    done
}

rm -rf "$LEDGER"
say "starting validator (phase A, genesis)"
start_validator "$LOGS/validator-a.log" --reset
wait_rpc
ok "validator up at slot $(solana slot -u "$RPC_URL")"

# ---------------------------------------------------------------------------
# Step 4: deploy (epoch 0) — all real txs incl. BLS PoP registrations
# ---------------------------------------------------------------------------
say "phase A: deploy"
"$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" deploy \
    --restaking-program-id "$RESTAKING_PROGRAM_ID" \
    --vault-program-id "$VAULT_PROGRAM_ID" \
    --ncn-program-id "$NCN_PROGRAM_ID" \
    --num-operators "$NUM_OPERATORS" \
    --base-port "$NODE_BASE_PORT" \
    --router-port "$ROUTER_PORT" | tee "$LOGS/deploy.log"

if [[ "$E2E_LLM" == "1" ]]; then
    # LLM leg bootstrap (still epoch 0): InitializeState for the settlement
    # consumer, then REGENERATE the payload with the real values (state PDA +
    # settle discriminator + transition_index 0). The story bytes, root and
    # provenance stay the checked-in fixture's ground truth — the EVM sim is
    # NOT re-run.
    if [[ "$LLM_MODEL" == "qwen" ]]; then
        say "phase A: qwen-init (settlement InitializeState + artifacts)"
        "$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" qwen-init \
            --fixture "$LLM_FIXTURE" \
            --settlement-program-id "$SETTLEMENT_PROGRAM_ID" | tee "$LOGS/llm-init.log"

        # shellcheck disable=SC1091
        source "$OUT/llm_env.sh"
        say "regenerating the qwen payload via llm-payload-producer (real state PDA + discriminator)"
        "$PRODUCER" --mode qwen \
            --prompt "$LLM_PROMPT" \
            --prompt-ids "$LLM_PROMPT_IDS" \
            --answer-ids "$LLM_ANSWER_IDS" \
            --answer-text "$LLM_ANSWER_TEXT" \
            --manifest "$LLM_MANIFEST_HEX" \
            --model "$LLM_MODEL_TAG" \
            --new-root "$LLM_NEW_ROOT_HEX" \
            --transition-index 0 \
            --state-pda "$LLM_STATE_PDA_HEX" \
            --ix-discriminator "$LLM_SETTLE_DISC_HEX" \
            --sim-command "$LLM_SIM_COMMAND" \
            --solidity-sdk-commit "$LLM_SDK_COMMIT" \
            --out "$OUT/llm_payload.json" | tee "$LOGS/llm-producer.log"
    else
        say "phase A: llm-init (settlement InitializeState + artifacts)"
        "$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" llm-init \
            --fixture "$LLM_FIXTURE" \
            --settlement-program-id "$SETTLEMENT_PROGRAM_ID" | tee "$LOGS/llm-init.log"

        # shellcheck disable=SC1091
        source "$OUT/llm_env.sh"
        say "regenerating the payload via llm-payload-producer (real state PDA + discriminator)"
        "$PRODUCER" \
            --prompt "$LLM_PROMPT" \
            --story-file "$OUT/story.txt" \
            --new-root "$LLM_NEW_ROOT_HEX" \
            --transition-index 0 \
            --state-pda "$LLM_STATE_PDA_HEX" \
            --ix-discriminator "$LLM_SETTLE_DISC_HEX" \
            --buffer "$LLM_BUFFER_PDA_HEX" \
            --sim-command "$LLM_SIM_COMMAND" \
            --solidity-sdk-commit "$LLM_SDK_COMMIT" \
            --out "$OUT/llm_payload.json" | tee "$LOGS/llm-producer.log"
    fi
    LLM_NEW_DIGEST=$(sed -n 's/.*"digest_hex": "\([0-9a-f]*\)".*/\1/p' "$OUT/llm_payload.json")
    ok "payload digest: $LLM_NEW_DIGEST (checked-in fixture had $LLM_CHECKED_IN_DIGEST_HEX — the state_pda/ix_discriminator placeholders became real)"
fi

# ---------------------------------------------------------------------------
# Step 5: restart with --warp-slot into epoch 2 (SlotToggles go Active)
# ---------------------------------------------------------------------------
# CRITICAL: a --warp-slot restart rebuilds the bank from the latest FULL
# SNAPSHOT ARCHIVE in the ledger dir (snapshot-<slot>-<hash>.tar.zst, taken
# every 100 slots — solana-test-validator 4.1.x exposes no interval flag);
# the blockstore tail past that snapshot is NOT replayed. Killing the
# validator before a snapshot covers the deploy tip silently drops the tail
# transactions (empirically verified: post-snapshot accounts vanish across a
# warp restart -> "Invalid account owner" in phase B). Wait for a covering
# snapshot before killing.
TIP_SLOT=$(solana slot -u "$RPC_URL")
say "waiting for a full snapshot archive covering the deploy tip (slot $TIP_SLOT)"
deadline=$((SECONDS + 600))
while :; do
    SNAP_SLOT=$(ls "$LEDGER"/snapshot-*.tar.zst 2>/dev/null \
        | sed -E 's/.*snapshot-([0-9]+)-.*/\1/' | sort -n | tail -1)
    [[ -n "${SNAP_SLOT:-}" && "$SNAP_SLOT" -ge "$TIP_SLOT" ]] && break
    [[ $SECONDS -lt $deadline ]] || fail "no snapshot >= slot $TIP_SLOT within 600s (latest: ${SNAP_SLOT:-none})"
    sleep 5
done
ok "snapshot at slot $SNAP_SLOT covers the deploy tip"

say "restarting validator with --warp-slot $WARP_SLOT (epoch 2)"
kill "$VALIDATOR_PID"; wait "$VALIDATOR_PID" 2>/dev/null || true
# NOTE: on an existing ledger the --bpf-program/--ticks-per-slot genesis
# flags are silently ignored; the restart only needs the ledger + warp slot.
solana-test-validator --ledger "$LEDGER" --warp-slot "$WARP_SLOT" --quiet \
    &> "$LOGS/validator-b.log" &
VALIDATOR_PID=$!
wait_rpc
SLOT_B=$(solana slot -u "$RPC_URL")
[[ "$SLOT_B" -ge "$WARP_SLOT" ]] || fail "warp restart landed at slot $SLOT_B < $WARP_SLOT"
ok "validator warped to slot $SLOT_B (epoch $((SLOT_B / EPOCH_LENGTH)))"

# ---------------------------------------------------------------------------
# Step 6: activate (vault update crank + NCN snapshot crank)
# ---------------------------------------------------------------------------
say "phase B: activate"
"$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" activate | tee "$LOGS/activate.log"

if [[ "$E2E_LLM" == "1" && "$LLM_MODEL" != "qwen" ]]; then
    # Stage the story bytes into the transition-0 buffer PDA. 457 bytes fit
    # one transaction; chunking at 256 B forces >= 2 WriteBuffer calls to
    # exercise the append path for real. (Qwen answers ride the event inline —
    # no buffer, nothing to stage.)
    say "phase B: llm-stage (chunked WriteBuffer)"
    "$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" llm-stage \
        --payload "$OUT/llm_payload.json" --chunk-size 256 | tee "$LOGS/llm-stage.log"
fi

# ---------------------------------------------------------------------------
# Step 7: router + nodes
# ---------------------------------------------------------------------------
say "starting $NUM_OPERATORS nodes + router"
export NCN_DEPLOYMENT_PATH="$OUT/ncn_deploy.json"
for i in $(seq 0 $((NUM_OPERATORS - 1))); do
    mkdir -p "$OUT/node-$i-data"
    (cd "$OUT" && STORAGE_DIR="$OUT/node-$i-data" \
        "$NODE_BIN" \
        --key-file "$OUT/node-$i.bls.json" \
        --port $((NODE_BASE_PORT + i)) \
        --router "$OUT/router-connection.json" &> "$LOGS/node-$i.log") &
    PIDS+=($!)
done
mkdir -p "$OUT/router-data"
(cd "$OUT" && STORAGE_DIR="$OUT/router-data" \
    SOLANA_PAYER_KEYPAIR="$OUT/authority.json" \
    "$ROUTER_BIN" \
    --key-file "$OUT/router.bls.json" \
    --port "$ROUTER_PORT" &> "$LOGS/router.log") &
PIDS+=($!)

# ---------------------------------------------------------------------------
# Step 8: assert — a successful VerifyCertificate on-chain at `confirmed`
# ---------------------------------------------------------------------------
say "waiting for an on-chain VerifyCertificate (confirmed)"
"$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" assert-verified --timeout-secs 300

if grep -q "verification finalized" "$LOGS/router.log"; then
    ok "router reported: $(grep -m1 'verification finalized' "$LOGS/router.log" | tail -c 200)"
fi
ok "SOLANA E2E PASSED — real BLS certificate verified on-chain by the NCN program"

# ---------------------------------------------------------------------------
# Step 9: LLM settlement leg — the story settles on-chain (INTERFACES.md §4)
# ---------------------------------------------------------------------------
if [[ "$E2E_LLM" == "1" ]]; then
    say "LLM leg: stopping the counter router + nodes (same committee, settle mode next)"
    for pid in "${PIDS[@]:-}"; do kill "$pid" 2>/dev/null || true; done
    pkill -f "counter-solana-node --key-file $OUT" 2>/dev/null || true
    pkill -f "counter-solana-router --key-file $OUT" 2>/dev/null || true
    PIDS=()
    sleep 3

    say "LLM leg: starting $NUM_OPERATORS nodes + router (LLM_SETTLE=1)"
    for i in $(seq 0 $((NUM_OPERATORS - 1))); do
        mkdir -p "$OUT/node-$i-llm-data"
        (cd "$OUT" && LLM_SETTLE=1 STORAGE_DIR="$OUT/node-$i-llm-data" \
            "$NODE_BIN" \
            --key-file "$OUT/node-$i.bls.json" \
            --port $((NODE_BASE_PORT + i)) \
            --router "$OUT/router-connection.json" &> "$LOGS/llm-node-$i.log") &
        PIDS+=($!)
    done
    mkdir -p "$OUT/router-llm-data"
    (cd "$OUT" && LLM_SETTLE=1 \
        LLM_PAYLOAD_FIXTURE="$OUT/llm_payload.json" \
        STORAGE_DIR="$OUT/router-llm-data" \
        SOLANA_PAYER_KEYPAIR="$OUT/authority.json" \
        "$ROUTER_BIN" \
        --key-file "$OUT/router.bls.json" \
        --port "$ROUTER_PORT" &> "$LOGS/llm-router.log") &
    PIDS+=($!)

    say "LLM leg: waiting for the settle to land (confirmed)"
    if [[ "$LLM_MODEL" == "qwen" ]]; then
        "$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" qwen-assert \
            --payload "$OUT/llm_payload.json" --timeout-secs 300 | tee "$LOGS/llm-assert.log"
    else
        "$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" llm-assert \
            --payload "$OUT/llm_payload.json" --timeout-secs 300 | tee "$LOGS/llm-assert.log"
    fi

    say "LLM leg: replay gate (identical Settle must fail InvalidTransitionIndex)"
    "$DEPLOYER" --rpc-url "$RPC_URL" --out-dir "$OUT" llm-replay | tee "$LOGS/llm-replay.log"

    [[ -f "$OUT/frontend-config.json" ]] || fail "frontend-config.json was not emitted"
    ok "frontend config: $OUT/frontend-config.json"
    sed 's/^/[e2e]   /' "$OUT/frontend-config.json"

    if [[ "$LLM_MODEL" == "qwen" ]]; then
        ok "SOLANA QWEN SETTLEMENT E2E PASSED — the real Qwen3-0.6B answer was certified by the 4-operator BLS committee and settled on-chain (digest $LLM_NEW_DIGEST)"
    else
        ok "SOLANA LLM SETTLEMENT E2E PASSED — the real Solidity LLM story was certified by the 4-operator BLS committee and settled on-chain (digest $LLM_NEW_DIGEST)"
    fi
fi
