apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: commonware-avs

resources:
  - ../../base

patches:
  - path: patches/image-pull-policy.yaml
  - path: patches/nodeport-services.yaml
  - path: patches/pvc-storage-class.yaml

images:
  - name: ghcr.io/breadchaincoop/commonware-avs-router
    newName: commonware-avs-router
    newTag: ci
  - name: ghcr.io/breadchaincoop/commonware-avs-node
    newName: commonware-avs-node
    newTag: ci
