apiVersion: v1
kind: Service
metadata:
  name: signer-svc
  namespace: commonware-avs
  labels:
    app: signer
spec:
  selector:
    app: signer
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 9081
      targetPort: 9081
  type: ClusterIP
