apiVersion: v1
kind: ServiceAccount
metadata:
  name: avs-service-account
  namespace: commonware-avs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader
  namespace: commonware-avs
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-reader-binding
  namespace: commonware-avs
subjects:
  - kind: ServiceAccount
    name: avs-service-account
    namespace: commonware-avs
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
